### ISSUE TITLE
Comment contrast

### ISSUE THREAD

**Issue by ardyfeb** [subtheme-pro/atom-one#1]
This theme is awesome and i love it, but comment color is hard to read
![rsz_screenshot_20200804_213716](https://user-images.githubusercontent.com/30074366/89308015-f6604280-d69b-11ea-9005-2e7533cf34ea.png)

**Comment by jontaydev** [comment]
Thanks for pointing this out, I'll fix this week. I just published recently and didn't have time to check over all of the syntax, so let me know if you see anything else.

**Comment by ardyfeb** [comment]
Thanks ! i really appreciate it and just got this inlay hints on parameter having bigger font size when using Dank Mono font
![rsz_1screenshot_20200805_070022](https://user-images.githubusercontent.com/30074366/89357402-9349cc80-d6ea-11ea-9958-993a43d87597.png)

**Comment by ardyfeb** [comment]
What font used on theme screenshot ?

**Comment by jontaydev** [comment]
Just pushed an update to JetBrains with the comment fix (I'm using the colors from the Atom One Pro on VSCode). You can also download the plugin before it gets approved from here: https://github.com/thematic-dev/atom-one/releases/tag/v0.2. Let me know if that looks better.

Also, the font is [Operator Mono](https://www.typography.com/fonts/operator/styles), but it's a paid font.

**Comment by ardyfeb** [comment]
Thanks @jontaydev awesome !!
