### ISSUE TITLE
Syntax color highlight disappears when code snippet is chosen.

### ISSUE THREAD

**Issue by MuggleWang** [subtheme-pro/atom-one#4]
Hi,
I found that the syntax color highlight disappears when code snippet is chosen, shown as below:
Before
![iShot2021-08-07 22 27 05](https://user-images.githubusercontent.com/22472622/128603513-52323c98-4b29-4b86-9a47-bc6ab6cfd304.png)
After
![iShot2021-08-07 22 27 21](https://user-images.githubusercontent.com/22472622/128603516-b247cbea-4ca7-4311-80d5-8ce79782eef9.png)

While the default theme by jetbrains keeps color even the snippet is chosen, shown as below:
Before
![iShot2021-08-07 22 27 49](https://user-images.githubusercontent.com/22472622/128603580-3baa9326-2d48-4cdf-b578-ad77032e7849.png)
After
![iShot2021-08-07 22 28 06](https://user-images.githubusercontent.com/22472622/128603584-f7131ede-7468-4192-a0f2-570b79bf8880.png)

Is that a feature or bug? Is there a way to keep syntax color highlight when code snippet is chosen?
Thanks!

**Comment by jontaydev** [comment]
Odd, I am seeing the syntax color show up when selected. Are you on the latest version of the theme (1.3.2)? Is this also on the latest version of PyCharm?

<img width="626" alt="Screen Shot 2021-08-07 at 6 40 38 PM" src="https://user-images.githubusercontent.com/2243530/128615547-1e6455c4-fb0d-4d12-bd69-46b334114f5c.png">

**Comment by jontaydev** [comment]
Oh never mind, I got my Monokai Pro theme confused with Atom One. Yea I see the issue, will fix. 

Thanks.

**Comment by jontaydev** [comment]
[Fixed](https://plugins.jetbrains.com/plugin/14799-atom-one-theme/versions/stable/131561)
